### PR TITLE
Sign Up page to create a basic auth user

### PR DESCRIPTION
**Pull request by samredai**
### Summary

This adds a signup form to the login screen that can be used to create a basic auth user (not using google oauth or github oauth). This gets us one step closer to always requiring auth and is worth serious consideration on if we want to do that in the OSS project as an alternative to what we recently agreed on in a recent sync--setting the user as "unknown" when auth is globally disabled.

In other words, creating a basic auth user through the signup page is such a low bar that maybe we can make it the lowest bar :)

https://github.com/DataJunction/dj/assets/43911210/018be113-b227-4582-8663-df0cda207e52

### Test Plan

Added UI tests for the signup page and tested signing up in the local docker demo environment.

- [x] PR has an associated issue: #697 
- [x] `make check` passes
- [x] `make test` shows 100% unit test coverage

### CODE REVIEW

**Review by CircArgs — APPROVED** [review]

**Comment by CircArgs** [comment]
Cool! Let's get rid of users being optional in routes and require basic auth?

**Comment by CircArgs** [comment]
Also the signing page reminds me of early 2000s sites. it looks like it belongs to 2000 Ebay:

**Comment by agorajek** [comment]
I think I like this idea! @betodealmeida do you have any thoughts from your OSS experience?

**Review by shangyian — APPROVED** [review]
Nice!

**Comment by samredai** [comment]
> Cool! Let's get rid of users being optional in routes and require basic auth?

Agreed. I was initially thinking to do this by injecting "unknown" when auth is disabled but requiring auth feels like the better path.

**Pull request merged**
