### PR TITLE
Update illustration

### PR DESCRIPTION
**Pull request by samredai**
### Summary

This updates the illustration to include some more varied outputs.

### Test Plan

N/A

- [x] PR has an associated issue: #296 
- [x] `make check` passes
- [x] `make test` shows 100% unit test coverage

### Deployment Plan

N/A

### CODE REVIEW

**Comment by shangyian** [comment]
Out of curiosity, if you click on the "less sloppy" option, what does it look like?

**Comment by samredai** [comment]
> Out of curiosity, if you click on the "less sloppy" option in Excalidraw, what does it look like?

image
👀

**Comment by shangyian** [comment]
Haha, I can't decide what's better... @agorajek what do you think?

**Review by shangyian — APPROVED** [review]

**Comment by samredai** [comment]
@shangyian updated it to the less sloppy one which looks much better (let me know if you disagree). I also included the `.excalidraw` file so we can make edits to it in the future.

**Comment by shangyian** [comment]
Ok with all the sloppinesses side-by-side, now my vote is least sloppy 😆

**Pull request merged**
