### PR TITLE
feat: pass env variables for reflection service and DJ core

### PR DESCRIPTION
**Pull request by sadath-12**
### Summary

Becomes easy when these components are separately deployed

### Test Plan

- [ ] PR has an associated issue: #
- [ ] `make check` passes
- [ ] `make test` shows 100% unit test coverage

### CODE REVIEW

**Comment by samredai** [comment]
@sadath-12 thanks for this PR. Can you expand on the PR description a bit? Is the purpose here so that you can have one centrally stored set of the same environment variables that you set for each of the different service types? You still intend to run these as separate services right? Also, should we add a `DJ_QUERY_` prefix to the query service settings object?

cc: @agorajek and @shangyian, existing deployments would need to add these prefixes to our env vars once this change is deployed.

**Comment by sadath-12** [comment]
> @sadath-12 thanks for this PR. Can you expand on the PR description a bit? Is the purpose here so that you can have one centrally stored set of the same environment variables that you set for each of the different service types? You still intend to run these as separate services right? Also, should we add a `DJ_QUERY_` prefix to the query service settings object?
> 
> cc: @agorajek and @shangyian, existing deployments would need to add these prefixes to our env vars once this change is deployed.

yes , we would deploy dj components separately which might not necessarily all be in same localhost . 
Also I was intending to add env variables as preference which would not change the default.

For query service it seemed fine since it doesn't call other services

**Comment by shangyian** [comment]
@sadath-12 I'm not sure why the prefix is needed? If these are all separate deployments, shouldn't each have their own `.env` file?

**Comment by sadath-12** [comment]
@shangyian I dint notice the feature of ```pydantic``` to automatically pick up env variables first . so I think this pr might not be necessary

**Comment by agorajek** [comment]
+1 to what @shangyian said.

**Pull request closed without merging**
