### PR TITLE
Squash alembic revisions

### PR DESCRIPTION
**Pull request by shangyian**
### Summary

Squash all alembic revisions. I tried to run the existing set of revisions against a CockroachDB cluster and came across a number of issues. For example, types cannot be recreated, but some of the existing revisions recreate `nodetype` when the enum is declared in the revision. In lieu of making changes to each of the individual revisions, I think it makes sense just to squash. (cc @betodealmeida)

@samredai I will wait for you to get your changes in before merging this. 

### Test Plan

Ran `alembic migrate head` against a Cockroach cluster.

- [X] PR has an associated issue: #301
- [X] `make check` passes
- [X] `make test` shows 100% unit test coverage

### CODE REVIEW

**Comment by samredai** [comment]
@shangyian I agree with doing this now. We've been aggressively making changes to the metadata model but with the node versioning and catalog/engine changes that are now in, I don't see any more major planned changes. That being said, a few may have to sneak in before the 0.1, but no reason why we can't squash again at that point.

**Review by samredai — APPROVED** [review]
I've merged my PRs so this should be good to go in now. 🚀

**Comment by agorajek** [comment]
Database migrations... so cool in theory, but so tough in practice.

**Comment by shangyian** [comment]
@agorajek Indeed! And we won't have this luxury when we have a real database going...

**Pull request merged**
